apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: go-demo 
  janus-idp.io/tekton: go-demo
  backstage.io/kubernetes-id: go-demo
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: go-demo
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml